export const testGroups = [
  // General
  { name: "The Boys", creator: "jmoney", members: Array.from({ length: 12 }, () => "") },
  { name: "Weekend Wagers", creator: "snacklord", members: Array.from({ length: 7 }, () => "") },
  { name: "the group chat", creator: "dontaskme", members: Array.from({ length: 24 }, () => "") },
  { name: "Friendly Competition", creator: "BigDawg42", members: Array.from({ length: 4 }, () => "") },
  { name: "Who Knows Best?", creator: "probablywrong", members: Array.from({ length: 18 }, () => "") },
  { name: "JUST FOR FUN", creator: "the_real_one", members: Array.from({ length: 31 }, () => "") },
  { name: "The Challenge", creator: "xXchaosXx", members: Array.from({ length: 9 }, () => "") },
  { name: "Anything Goes", creator: "yeetmaster", members: Array.from({ length: 43 }, () => "") },
  { name: "Call It", creator: "mikey_42", members: Array.from({ length: 15 }, () => "") },
  { name: "Predictions", creator: "guessagain", members: Array.from({ length: 2 }, () => "") },
  { name: "place your bets", creator: "lowkeylegend", members: Array.from({ length: 27 }, () => "") },
  { name: "The Prediction Club", creator: "not_a_bot", members: Array.from({ length: 36 }, () => "") },
  { name: "Guess We'll See", creator: "maybe_later", members: Array.from({ length: 6 }, () => "") },
  { name: "Chaos", creator: "chaos.exe", members: Array.from({ length: 48 }, () => "") },
  { name: "Picks", creator: "just_here_for_coins", members: Array.from({ length: 21 }, () => "") },

  // Friends / private
  { name: "The Homies", creator: "brotherman", members: Array.from({ length: 8 }, () => "") },
  { name: "the inner circle", creator: "privateszn", members: Array.from({ length: 3 }, () => "") },
  { name: "The Usual Suspects", creator: "suspect_01", members: Array.from({ length: 17 }, () => "") },
  { name: "The Squad", creator: "bighead", members: Array.from({ length: 29 }, () => "") },
  { name: "NO NEW FRIENDS", creator: "stayback", members: Array.from({ length: 5 }, () => "") },
  { name: "No Screenshots", creator: "trustmebro", members: Array.from({ length: 11 }, () => "") },
  { name: "keep it in the group", creator: "classified_7", members: Array.from({ length: 34 }, () => "") },
  { name: "Don't Tell The Others", creator: "iykyk", members: Array.from({ length: 20 }, () => "") },
  { name: "You Had To Be There", creator: "storytime", members: Array.from({ length: 46 }, () => "") },
  { name: "the gc", creator: "who_invited_me", members: Array.from({ length: 14 }, () => "") },
  { name: "Us", creator: "justtheboys", members: Array.from({ length: 1 }, () => "") },
  { name: "THE GROUP", creator: "OGmember", members: Array.from({ length: 25 }, () => "") },

  // School
  { name: "The Dorm Room", creator: "roomie", members: Array.from({ length: 10 }, () => "") },
  { name: "Roommate Rumble", creator: "dishwasher_king", members: Array.from({ length: 22 }, () => "") },
  { name: "study break", creator: "barely_passing", members: Array.from({ length: 16 }, () => "") },
  { name: "No Sleep Club", creator: "awake_again", members: Array.from({ length: 38 }, () => "") },
  { name: "After Class", creator: "backrow", members: Array.from({ length: 7 }, () => "") },
  { name: "The Study Group", creator: "notes_app", members: Array.from({ length: 13 }, () => "") },
  { name: "the 8 AM survivors", creator: "sleepdeprived", members: Array.from({ length: 4 }, () => "") },
  { name: "CAFFEINE REQUIRED", creator: "coffee_addict", members: Array.from({ length: 32 }, () => "") },
  { name: "Class", creator: "here_again", members: Array.from({ length: 19 }, () => "") },
  { name: "Finals", creator: "send_help", members: Array.from({ length: 41 }, () => "") },

  // Roommates
  { name: "Who Left The Light On?", creator: "not_me", members: Array.from({ length: 6 }, () => "") },
  { name: "Who's Cooking?", creator: "chef_boy_r_d", members: Array.from({ length: 2 }, () => "") },
  { name: "Chores", creator: "procrastinator", members: Array.from({ length: 4 }, () => "") },
  { name: "the fridge", creator: "midnight_snacker", members: Array.from({ length: 9 }, () => "") },
  { name: "Roommate Olympics", creator: "roomie_olympian", members: Array.from({ length: 5 }, () => "") },
  { name: "Who Ate My Food?", creator: "hands_off", members: Array.from({ length: 3 }, () => "") },
  { name: "Dishwasher Debate", creator: "plate_destroyer", members: Array.from({ length: 8 }, () => "") },
  { name: "WHO'S TAKING OUT THE TRASH", creator: "trashman", members: Array.from({ length: 12 }, () => "") },
  { name: "the thermostat", creator: "68degrees", members: Array.from({ length: 4 }, () => "") },
  { name: "Apartment", creator: "unit_2b", members: Array.from({ length: 7 }, () => "") },

  // Food / delivery
  { name: "What's For Dinner?", creator: "hungry_af", members: Array.from({ length: 15 }, () => "") },
  { name: "DoorDash Watch", creator: "deliveryguy", members: Array.from({ length: 28 }, () => "") },
  { name: "when's it getting here?", creator: "tracking_number", members: Array.from({ length: 6 }, () => "") },
  { name: "Pizza Night", creator: "extra_cheese", members: Array.from({ length: 18 }, () => "") },
  { name: "Taco Tuesday", creator: "tacobellfan", members: Array.from({ length: 11 }, () => "") },
  { name: "ICE CREAM CHALLENGE", creator: "conehead", members: Array.from({ length: 23 }, () => "") },
  { name: "How Many Cones?", creator: "sweettooth", members: Array.from({ length: 37 }, () => "") },
  { name: "Who Gets The Last One?", creator: "last_slice", members: Array.from({ length: 5 }, () => "") },
  { name: "Late Night Eats", creator: "2am_snack", members: Array.from({ length: 14 }, () => "") },
  { name: "Snack Attack", creator: "snackpack", members: Array.from({ length: 26 }, () => "") },
  { name: "Food", creator: "eat_first", members: Array.from({ length: 2 }, () => "") },
  { name: "what are we ordering", creator: "idk_you_pick", members: Array.from({ length: 33 }, () => "") },

  // Random / everyday
  { name: "How Many?", creator: "numberguy", members: Array.from({ length: 9 }, () => "") },
  { name: "Guess The Number", creator: "guessmaster", members: Array.from({ length: 16 }, () => "") },
  { name: "Can He Do It?", creator: "watch_this", members: Array.from({ length: 3 }, () => "") },
  { name: "Bet You Can't", creator: "hold_my_drink", members: Array.from({ length: 42 }, () => "") },
  { name: "one more try", creator: "againagain", members: Array.from({ length: 8 }, () => "") },
  { name: "Longest Streak", creator: "streaky", members: Array.from({ length: 21 }, () => "") },
  { name: "First One There", creator: "earlybird", members: Array.from({ length: 5 }, () => "") },
  { name: "How Long Will It Take?", creator: "timekeeper", members: Array.from({ length: 30 }, () => "") },
  { name: "OVER UNDER EVERYTHING", creator: "the_oddsmaker", members: Array.from({ length: 47 }, () => "") },
  { name: "Higher or Lower", creator: "pick_one", members: Array.from({ length: 13 }, () => "") },
  { name: "Numbers", creator: "count_it", members: Array.from({ length: 24 }, () => "") },
  { name: "GUESS", creator: "take_a_guess", members: Array.from({ length: 1 }, () => "") },

  // Personal predictions
  { name: "When Will He Call?", creator: "ringring", members: Array.from({ length: 17 }, () => "") },
  { name: "How Many Calls?", creator: "phone_addict", members: Array.from({ length: 6 }, () => "") },
  { name: "Who's Calling Next?", creator: "unknown_number", members: Array.from({ length: 12 }, () => "") },
  { name: "Will She Show Up?", creator: "maybe_she_will", members: Array.from({ length: 31 }, () => "") },
  { name: "what time will he get here?", creator: "running_late", members: Array.from({ length: 4 }, () => "") },
  { name: "Will They Be Late?", creator: "always_late", members: Array.from({ length: 19 }, () => "") },
  { name: "When Will Mom Text?", creator: "family_group", members: Array.from({ length: 9 }, () => "") },
  { name: "How Long Until He Replies?", creator: "left_on_read", members: Array.from({ length: 27 }, () => "") },
  { name: "Who's Going To Cancel?", creator: "flaky_friends", members: Array.from({ length: 14 }, () => "") },
  { name: "Who Falls Asleep First?", creator: "napking", members: Array.from({ length: 2 }, () => "") },
  { name: "Who's Bringing Snacks?", creator: "snack_duty", members: Array.from({ length: 22 }, () => "") },
  { name: "calls", creator: "ringtone", members: Array.from({ length: 7 }, () => "") },
  { name: "Late", creator: "five_more_minutes", members: Array.from({ length: 38 }, () => "") },

  // Events / plans
  { name: "Saturday Plans", creator: "weekendwarrior", members: Array.from({ length: 18 }, () => "") },
  { name: "Friday Night", creator: "fridaykid", members: Array.from({ length: 26 }, () => "") },
  { name: "the weekend", creator: "outandabout", members: Array.from({ length: 5 }, () => "") },
  { name: "Game Night", creator: "controller_1", members: Array.from({ length: 13 }, () => "") },
  { name: "Movie Night", creator: "popcornpls", members: Array.from({ length: 34 }, () => "") },
  { name: "Pool Day", creator: "floatie", members: Array.from({ length: 8 }, () => "") },
  { name: "Beach Day", creator: "sunscreen", members: Array.from({ length: 20 }, () => "") },
  { name: "Cabin Weekend", creator: "woodsman", members: Array.from({ length: 3 }, () => "") },
  { name: "Lake House", creator: "dockrat", members: Array.from({ length: 29 }, () => "") },
  { name: "Road Trip", creator: "shotgun", members: Array.from({ length: 11 }, () => "") },
  { name: "Vegas Weekend", creator: "highrollerish", members: Array.from({ length: 44 }, () => "") },
  { name: "The Trip", creator: "carry_on_only", members: Array.from({ length: 16 }, () => "") },
  { name: "Who's Driving?", creator: "designated", members: Array.from({ length: 6 }, () => "") },
  { name: "Plans", creator: "whats_the_plan", members: Array.from({ length: 23 }, () => "") },

  // Private / inside jokes
  { name: "The Blue Couch", creator: "couchguy", members: Array.from({ length: 4 }, () => "") },
  { name: "room 302", creator: "three_oh_two", members: Array.from({ length: 7 }, () => "") },
  { name: "The Green Folder", creator: "folder_nerd", members: Array.from({ length: 15 }, () => "") },
  { name: "Table 7", creator: "table_seven", members: Array.from({ length: 3 }, () => "") },
  { name: "the back booth", creator: "boothcrew", members: Array.from({ length: 10 }, () => "") },
  { name: "Thursday At 9", creator: "thursdaykid", members: Array.from({ length: 28 }, () => "") },
  { name: "The Red Hat", creator: "redhatguy", members: Array.from({ length: 6 }, () => "") },
  { name: "The Upstairs Crew", creator: "upstairs", members: Array.from({ length: 17 }, () => "") },
  { name: "Friday At Jake's", creator: "jakes_place", members: Array.from({ length: 21 }, () => "") },
  { name: "The Basement", creator: "basement_dweller", members: Array.from({ length: 2 }, () => "") },
  { name: "Parking Lot Legends", creator: "lot_lizard", members: Array.from({ length: 39 }, () => "") },
  { name: "The Committee", creator: "committee_member", members: Array.from({ length: 12 }, () => "") },
  { name: "Meeting Adjourned", creator: "motion_denied", members: Array.from({ length: 5 }, () => "") },
  { name: "Project X", creator: "agent_unknown", members: Array.from({ length: 32 }, () => "") },
  { name: "Operation Sunday", creator: "sunday_service", members: Array.from({ length: 8 }, () => "") },
  { name: "CLASSIFIED", creator: "top_secret", members: Array.from({ length: 46 }, () => "") },
  { name: "The Table", creator: "seat_taken", members: Array.from({ length: 14 }, () => "") },
  { name: "same place same time", creator: "usual_spot", members: Array.from({ length: 24 }, () => "") },
  { name: "Thursday Tradition", creator: "thursday_only", members: Array.from({ length: 9 }, () => "") },
  { name: "The Usual Spot", creator: "you_know_where", members: Array.from({ length: 18 }, () => "") },
  { name: "don't ask questions", creator: "dontaskquestions", members: Array.from({ length: 1 }, () => "") },
  { name: "You Know The Rules", creator: "rules_are_rules", members: Array.from({ length: 27 }, () => "") },
  { name: "The Original Group", creator: "og_since_day1", members: Array.from({ length: 36 }, () => "") },
  { name: "We Know What We're Doing", creator: "trust_the_plan", members: Array.from({ length: 11 }, () => "") },
  { name: "Definitely Not Cheating", creator: "nothing_to_see", members: Array.from({ length: 43 }, () => "") },

  // Family
  { name: "Family Picks", creator: "fam_account", members: Array.from({ length: 16 }, () => "") },
  { name: "the family group", creator: "cousin_it", members: Array.from({ length: 8 }, () => "") },
  { name: "Sunday At Grandma's", creator: "sundaykid", members: Array.from({ length: 4 }, () => "") },
  { name: "Cousins Only", creator: "cousincrew", members: Array.from({ length: 22 }, () => "") },
  { name: "Family Vacation", creator: "packed_bags", members: Array.from({ length: 13 }, () => "") },
  { name: "Who's Bringing What?", creator: "forgotten_item", members: Array.from({ length: 7 }, () => "") },
  { name: "Thanksgiving", creator: "turkeyday", members: Array.from({ length: 35 }, () => "") },
  { name: "Christmas Chaos", creator: "elf_mode", members: Array.from({ length: 19 }, () => "") },
  { name: "Holiday Challenge", creator: "holiday_mode", members: Array.from({ length: 3 }, () => "") },
  { name: "The Cousins", creator: "cousinsquad", members: Array.from({ length: 30 }, () => "") },

  // Work
  { name: "The Office", creator: "cubicle_king", members: Array.from({ length: 12 }, () => "") },
  { name: "Lunch Break", creator: "lunch_guy", members: Array.from({ length: 6 }, () => "") },
  { name: "Who's Getting Coffee?", creator: "coffee_run", members: Array.from({ length: 9 }, () => "") },
  { name: "Friday At Five", creator: "clockwatcher", members: Array.from({ length: 25 }, () => "") },
  { name: "OFFICE OLYMPICS", creator: "corporate_athlete", members: Array.from({ length: 41 }, () => "") },
  { name: "Who's Leaving Early?", creator: "outta_here", members: Array.from({ length: 14 }, () => "") },
  { name: "the break room", creator: "breakroomboss", members: Array.from({ length: 5 }, () => "") },
  { name: "After Work", creator: "clocked_out", members: Array.from({ length: 18 }, () => "") },
  { name: "The Team", creator: "team_player", members: Array.from({ length: 33 }, () => "") },
  { name: "Meeting Survivors", creator: "meeting_survivor", members: Array.from({ length: 10 }, () => "") },

  // Chaotic / funny
  { name: "Bad Decisions", creator: "badidea", members: Array.from({ length: 7 }, () => "") },
  { name: "Questionable Choices", creator: "questionable", members: Array.from({ length: 16 }, () => "") },
  { name: "Probably Fine", creator: "probably_fine", members: Array.from({ length: 4 }, () => "") },
  { name: "WE ARE SO BACK", creator: "comebackkid", members: Array.from({ length: 48 }, () => "") },
  { name: "This Is The One", creator: "trustme123", members: Array.from({ length: 13 }, () => "") },
  { name: "Absolutely Cooked", creator: "cooked_af", members: Array.from({ length: 29 }, () => "") },
  { name: "Down Bad", creator: "downbad", members: Array.from({ length: 8 }, () => "") },
  { name: "Trust Me", creator: "source_trustme", members: Array.from({ length: 21 }, () => "") },
  { name: "Send It", creator: "send_it", members: Array.from({ length: 3 }, () => "") },
  { name: "We Ride", creator: "ride_or_die", members: Array.from({ length: 37 }, () => "") },
  { name: "No Sweat", creator: "ezpz", members: Array.from({ length: 11 }, () => "") },
  { name: "Easy Money", creator: "free_coins", members: Array.from({ length: 26 }, () => "") },
  { name: "Free Money", creator: "moneyprinter", members: Array.from({ length: 5 }, () => "") },
  { name: "just one more", creator: "one_more_bro", members: Array.from({ length: 17 }, () => "") },
  { name: "How Bad Could It Be?", creator: "whatcouldgowrong", members: Array.from({ length: 42 }, () => "") },
  { name: "WE BALL", creator: "balling", members: Array.from({ length: 9 }, () => "") },
  { name: "It Could Happen", creator: "anythingpossible", members: Array.from({ length: 23 }, () => "") },
  { name: "Never In Doubt", creator: "neverwrong", members: Array.from({ length: 2 }, () => "") },
  { name: "Trust The Process", creator: "trusttheprocess", members: Array.from({ length: 34 }, () => "") },

  // Niche everyday predictions
  { name: "How Many Times Will He Say It?", creator: "counting_words", members: Array.from({ length: 15 }, () => "") },
  { name: "Who's Going To Laugh First?", creator: "cant_stop_laughing", members: Array.from({ length: 6 }, () => "") },
  { name: "Who Falls First?", creator: "watch_your_step", members: Array.from({ length: 12 }, () => "") },
  { name: "First One To 10", creator: "race_to_ten", members: Array.from({ length: 4 }, () => "") },
  { name: "How Long Is The Line?", creator: "linewatcher", members: Array.from({ length: 27 }, () => "") },
  { name: "when will it rain?", creator: "weather_guy", members: Array.from({ length: 19 }, () => "") },
  { name: "What Color Will She Wear?", creator: "colorpicker", members: Array.from({ length: 8 }, () => "") },
  { name: "Who Gets The Window Seat?", creator: "windowseat", members: Array.from({ length: 31 }, () => "") },
  { name: "Who Orders First?", creator: "orderup", members: Array.from({ length: 3 }, () => "") },
  { name: "Who's Picking The Movie?", creator: "movienightboss", members: Array.from({ length: 22 }, () => "") },
  { name: "How Many Photos?", creator: "photodump", members: Array.from({ length: 14 }, () => "") },
  { name: "Who's Going To Forget?", creator: "forgot_again", members: Array.from({ length: 38 }, () => "") },
  { name: "When Will The Package Arrive?", creator: "packagewatch", members: Array.from({ length: 10 }, () => "") },
  { name: "Who Gets There Last?", creator: "always_last", members: Array.from({ length: 24 }, () => "") },
  { name: "How Many People Show?", creator: "rollcall", members: Array.from({ length: 7 }, () => "") },
  { name: "Will It Fit?", creator: "measure_twice", members: Array.from({ length: 17 }, () => "") },
  { name: "Who Says It First?", creator: "say_it", members: Array.from({ length: 5 }, () => "") },
  { name: "How Many Attempts?", creator: "try_again", members: Array.from({ length: 28 }, () => "") },
  { name: "Who's Going To Win The Argument?", creator: "argument_king", members: Array.from({ length: 13 }, () => "") },
  { name: "Who has to pay?", creator: "not_me", members: Array.from({ length: 2 }, () => "") },
  { name: "who's gonna be late", creator: "five_minutes", members: Array.from({ length: 9 }, () => "") },
  { name: "First", creator: "firstplace", members: Array.from({ length: 1 }, () => "") },
  { name: "Last", creator: "last_one", members: Array.from({ length: 6 }, () => "") },
  { name: "HOW MANY", creator: "countingagain", members: Array.from({ length: 20 }, () => "") },
  { name: "Timing", creator: "right_on_time", members: Array.from({ length: 32 }, () => "") },
  { name: "Guess", creator: "take_a_shot", members: Array.from({ length: 11 }, () => "") },
  { name: "Over/Under", creator: "line_maker", members: Array.from({ length: 45 }, () => "") },
  { name: "Who's Next?", creator: "next_up", members: Array.from({ length: 18 }, () => "") }
];